name: manim_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - manim
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pycairo
  - moderngl
  - moderngl-window
  - glcontext
  - qiskit
  - pyqt
  - pyyaml
  - sympy
  - rustworkx
  - dill
  - typing-extensions
  - tqdm
  - watchdog
  - screeninfo
  - rich
  - requests
  - filelock
  - pyglet
  - pip:
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.15
      - pyqt5-sip==12.15.0
